name: Build Image

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    paths-ignore:
      - 'manual-build/**'
      - 'latest/**'
  workflow_dispatch:

env:
  ENDPOINT: "jodoll/docker-ripper-audio"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: whoan/docker-build-with-cache-action@v6
        with:
          username: "${{ secrets.DOCKERUSER }}"
          password: "${{ secrets.DOCKERPASS }}"
          image_name: "${{ env.ENDPOINT }}"
          image_tag: latest
          context: "./"
          dockerfile: "./audio/Dockerfile"
          stages_image_name: "jodoll/cache-ripper-latest"
